import type { Metadata } from "next";
import "./globals.css";
import UserContextProvider from "./components/usercontext";
import { RootProvider } from "fumadocs-ui/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        // you can use Tailwind CSS too
        style={{
          display: 'flex',
          flexDirection: 'column',
          minHeight: '100vh',
        }}
      >
        <RootProvider>
          <UserContextProvider>{children}</UserContextProvider>
        </RootProvider>
      </body>
    </html>
  );
}
