
import type { Metadata } from "next";
import "./globals.css";
import { User } from "./lib/types";
import UserContextProvider, { UserContext } from "./components/usercontext";
import { poppins } from "./lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`} suppressHydrationWarning>
       <UserContextProvider> {children}</UserContextProvider>
      </body>
    </html>
  );
}
